Feature/navigation
mash-up-kr/mash-up-admin-fe pull request #34
Opened 2022-02-11 10:09 UTC by mango906

## 변경사항

- Naviagation 컴포넌트를 추가하였습니다.
- 시안 상 사이즈가 있진 않았지만 전역적으로 쓸 헤더, 페이지 안에 들어갈 네비게이션 기준으로 sm, md으로 만들어서 사용하였습니다.
  - 만약 다른 화면에서 또 쓰일 경우 추가적인 개발이 필요할 수 도있는데, 그런 상황이 생기면 대응하기로 합의봤습니다.

### 작업 유형

- 신규 기능 추가

### 체크리스트

- [ ] Merge 할 브랜치가 올바른가?
- [ ] [코딩컨벤션](https://github.com/mash-up-kr/mash-up-recruit-fe/wiki/Coding-Convention)을 준수하였는가?
- [ ] 해당 PR과 관련없는 변경사항이 없는가? (만약 있다면 제목이나 변경사항에 기술하여 주세요.)
- [ ] 실행시 console 창에 에러나 경고가 없는것을 확인하였는가? (개발에 필요하여 고의적으로 남겨둔것 제외)

2022-02-11 19:15 UTC, dididy requested changes

2022-02-11 19:15 UTC, dididy commented on src/components/common/Navigation/Navigation.component.tsx
> +const Navigation = ({ size, inActiveColor, items, showBorder = true }: NavigationProps) => {
[제안]
이 브랜치에서는 defaultProps를 사용하지 않네요 하나로 통일하면 좋을 것 같아요!

https://github.com/mash-up-kr/mash-up-admin-fe/pull/31#discussion_r804934059

2022-02-11 19:15 UTC, dididy commented on src/components/common/Navigation/Navigation.styled.ts
> +          border-bottom: 1px solid ${theme.colors.gray30};
[제안]
rem으로 변경하면 좋을 것 같아요

2022-02-12 08:02 UTC, mango906 commented on src/components/common/Navigation/Navigation.component.tsx
> +const Navigation = ({ size, inActiveColor, items, showBorder = true }: NavigationProps) => {
https://github.com/mash-up-kr/mash-up-admin-fe/pull/31#discussion_r805132796 defaultProps때문에 린트에러가 났어서 저기선 저렇게 써줬었는데 최신기준 리베이스 받으니 잘 작동해서 저쪽에서 수정해줬어요 https://github.com/mash-up-kr/mash-up-admin-fe/pull/31#discussion_r805132796

2022-02-12 08:04 UTC, mango906 commented on src/components/common/Navigation/Navigation.styled.ts
> +          border-bottom: 1px solid ${theme.colors.gray30};
딴건 다 써주는데 border는 자꾸 무의식적으로 1px로 쓰고 있네요 ㅠㅠ 수정했습니다!

2022-02-12 10:06 UTC, minsour commented on src/components/common/Navigation/Navigation.component.tsx
> +  showBorder?: boolean;
showBorder 보다 showBottomBorder가 적절해 보이는데 어떠실까요?

2022-02-12 16:11 UTC, dididy approved these changes
👍 👍

2022-02-12 16:15 UTC, HaJunRyu approved these changes
👍

2022-02-12 16:15 UTC, HaJunRyu commented on src/components/common/Navigation/Navigation.component.tsx
> +  to: string;
to에 대한 상수를 정의하여 타입으로 사용해준다면 컴포넌트를 사용하는 입장에서도 더 편할 수 있을것 같아요 :)

2022-02-12 16:17 UTC, mango906 commented on src/components/common/Navigation/Navigation.component.tsx
> +  to: string;
요거 나중에 페이지 추가될 때 Routes 만들 예정인데 그떄 변경하도록 하겠습니다!

2022-02-12 16:18 UTC, merged